/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VietnameseFoodRouteImport } from './routes/vietnamese-food'
import { Route as SweetDessertsRouteImport } from './routes/sweet-desserts'
import { Route as SmoothiesRouteImport } from './routes/smoothies'
import { Route as PennywortRouteImport } from './routes/pennywort'
import { Route as NewDrinkRouteImport } from './routes/new-drink'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as MatchaRouteImport } from './routes/matcha'
import { Route as IcedCoffeeRouteImport } from './routes/iced-coffee'
import { Route as IceBlendedRouteImport } from './routes/ice-blended'
import { Route as FruitDrinksTeaRouteImport } from './routes/fruit-drinks-tea'
import { Route as FreshJuiceRouteImport } from './routes/fresh-juice'
import { Route as FoodRouteImport } from './routes/food'
import { Route as EspressoHotRouteImport } from './routes/espresso-hot'
import { Route as DessertsRouteImport } from './routes/desserts'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CoffeeRouteImport } from './routes/coffee'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const VietnameseFoodRoute = VietnameseFoodRouteImport.update({
  id: '/vietnamese-food',
  path: '/vietnamese-food',
  getParentRoute: () => rootRouteImport,
} as any)
const SweetDessertsRoute = SweetDessertsRouteImport.update({
  id: '/sweet-desserts',
  path: '/sweet-desserts',
  getParentRoute: () => rootRouteImport,
} as any)
const SmoothiesRoute = SmoothiesRouteImport.update({
  id: '/smoothies',
  path: '/smoothies',
  getParentRoute: () => rootRouteImport,
} as any)
const PennywortRoute = PennywortRouteImport.update({
  id: '/pennywort',
  path: '/pennywort',
  getParentRoute: () => rootRouteImport,
} as any)
const NewDrinkRoute = NewDrinkRouteImport.update({
  id: '/new-drink',
  path: '/new-drink',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchaRoute = MatchaRouteImport.update({
  id: '/matcha',
  path: '/matcha',
  getParentRoute: () => rootRouteImport,
} as any)
const IcedCoffeeRoute = IcedCoffeeRouteImport.update({
  id: '/iced-coffee',
  path: '/iced-coffee',
  getParentRoute: () => rootRouteImport,
} as any)
const IceBlendedRoute = IceBlendedRouteImport.update({
  id: '/ice-blended',
  path: '/ice-blended',
  getParentRoute: () => rootRouteImport,
} as any)
const FruitDrinksTeaRoute = FruitDrinksTeaRouteImport.update({
  id: '/fruit-drinks-tea',
  path: '/fruit-drinks-tea',
  getParentRoute: () => rootRouteImport,
} as any)
const FreshJuiceRoute = FreshJuiceRouteImport.update({
  id: '/fresh-juice',
  path: '/fresh-juice',
  getParentRoute: () => rootRouteImport,
} as any)
const FoodRoute = FoodRouteImport.update({
  id: '/food',
  path: '/food',
  getParentRoute: () => rootRouteImport,
} as any)
const EspressoHotRoute = EspressoHotRouteImport.update({
  id: '/espresso-hot',
  path: '/espresso-hot',
  getParentRoute: () => rootRouteImport,
} as any)
const DessertsRoute = DessertsRouteImport.update({
  id: '/desserts',
  path: '/desserts',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CoffeeRoute = CoffeeRouteImport.update({
  id: '/coffee',
  path: '/coffee',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/coffee': typeof CoffeeRoute
  '/contact': typeof ContactRoute
  '/desserts': typeof DessertsRoute
  '/espresso-hot': typeof EspressoHotRoute
  '/food': typeof FoodRoute
  '/fresh-juice': typeof FreshJuiceRoute
  '/fruit-drinks-tea': typeof FruitDrinksTeaRoute
  '/ice-blended': typeof IceBlendedRoute
  '/iced-coffee': typeof IcedCoffeeRoute
  '/matcha': typeof MatchaRoute
  '/menu': typeof MenuRoute
  '/new-drink': typeof NewDrinkRoute
  '/pennywort': typeof PennywortRoute
  '/smoothies': typeof SmoothiesRoute
  '/sweet-desserts': typeof SweetDessertsRoute
  '/vietnamese-food': typeof VietnameseFoodRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/coffee': typeof CoffeeRoute
  '/contact': typeof ContactRoute
  '/desserts': typeof DessertsRoute
  '/espresso-hot': typeof EspressoHotRoute
  '/food': typeof FoodRoute
  '/fresh-juice': typeof FreshJuiceRoute
  '/fruit-drinks-tea': typeof FruitDrinksTeaRoute
  '/ice-blended': typeof IceBlendedRoute
  '/iced-coffee': typeof IcedCoffeeRoute
  '/matcha': typeof MatchaRoute
  '/menu': typeof MenuRoute
  '/new-drink': typeof NewDrinkRoute
  '/pennywort': typeof PennywortRoute
  '/smoothies': typeof SmoothiesRoute
  '/sweet-desserts': typeof SweetDessertsRoute
  '/vietnamese-food': typeof VietnameseFoodRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/coffee': typeof CoffeeRoute
  '/contact': typeof ContactRoute
  '/desserts': typeof DessertsRoute
  '/espresso-hot': typeof EspressoHotRoute
  '/food': typeof FoodRoute
  '/fresh-juice': typeof FreshJuiceRoute
  '/fruit-drinks-tea': typeof FruitDrinksTeaRoute
  '/ice-blended': typeof IceBlendedRoute
  '/iced-coffee': typeof IcedCoffeeRoute
  '/matcha': typeof MatchaRoute
  '/menu': typeof MenuRoute
  '/new-drink': typeof NewDrinkRoute
  '/pennywort': typeof PennywortRoute
  '/smoothies': typeof SmoothiesRoute
  '/sweet-desserts': typeof SweetDessertsRoute
  '/vietnamese-food': typeof VietnameseFoodRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/coffee'
    | '/contact'
    | '/desserts'
    | '/espresso-hot'
    | '/food'
    | '/fresh-juice'
    | '/fruit-drinks-tea'
    | '/ice-blended'
    | '/iced-coffee'
    | '/matcha'
    | '/menu'
    | '/new-drink'
    | '/pennywort'
    | '/smoothies'
    | '/sweet-desserts'
    | '/vietnamese-food'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/coffee'
    | '/contact'
    | '/desserts'
    | '/espresso-hot'
    | '/food'
    | '/fresh-juice'
    | '/fruit-drinks-tea'
    | '/ice-blended'
    | '/iced-coffee'
    | '/matcha'
    | '/menu'
    | '/new-drink'
    | '/pennywort'
    | '/smoothies'
    | '/sweet-desserts'
    | '/vietnamese-food'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/coffee'
    | '/contact'
    | '/desserts'
    | '/espresso-hot'
    | '/food'
    | '/fresh-juice'
    | '/fruit-drinks-tea'
    | '/ice-blended'
    | '/iced-coffee'
    | '/matcha'
    | '/menu'
    | '/new-drink'
    | '/pennywort'
    | '/smoothies'
    | '/sweet-desserts'
    | '/vietnamese-food'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CoffeeRoute: typeof CoffeeRoute
  ContactRoute: typeof ContactRoute
  DessertsRoute: typeof DessertsRoute
  EspressoHotRoute: typeof EspressoHotRoute
  FoodRoute: typeof FoodRoute
  FreshJuiceRoute: typeof FreshJuiceRoute
  FruitDrinksTeaRoute: typeof FruitDrinksTeaRoute
  IceBlendedRoute: typeof IceBlendedRoute
  IcedCoffeeRoute: typeof IcedCoffeeRoute
  MatchaRoute: typeof MatchaRoute
  MenuRoute: typeof MenuRoute
  NewDrinkRoute: typeof NewDrinkRoute
  PennywortRoute: typeof PennywortRoute
  SmoothiesRoute: typeof SmoothiesRoute
  SweetDessertsRoute: typeof SweetDessertsRoute
  VietnameseFoodRoute: typeof VietnameseFoodRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vietnamese-food': {
      id: '/vietnamese-food'
      path: '/vietnamese-food'
      fullPath: '/vietnamese-food'
      preLoaderRoute: typeof VietnameseFoodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sweet-desserts': {
      id: '/sweet-desserts'
      path: '/sweet-desserts'
      fullPath: '/sweet-desserts'
      preLoaderRoute: typeof SweetDessertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/smoothies': {
      id: '/smoothies'
      path: '/smoothies'
      fullPath: '/smoothies'
      preLoaderRoute: typeof SmoothiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pennywort': {
      id: '/pennywort'
      path: '/pennywort'
      fullPath: '/pennywort'
      preLoaderRoute: typeof PennywortRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new-drink': {
      id: '/new-drink'
      path: '/new-drink'
      fullPath: '/new-drink'
      preLoaderRoute: typeof NewDrinkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matcha': {
      id: '/matcha'
      path: '/matcha'
      fullPath: '/matcha'
      preLoaderRoute: typeof MatchaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iced-coffee': {
      id: '/iced-coffee'
      path: '/iced-coffee'
      fullPath: '/iced-coffee'
      preLoaderRoute: typeof IcedCoffeeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ice-blended': {
      id: '/ice-blended'
      path: '/ice-blended'
      fullPath: '/ice-blended'
      preLoaderRoute: typeof IceBlendedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fruit-drinks-tea': {
      id: '/fruit-drinks-tea'
      path: '/fruit-drinks-tea'
      fullPath: '/fruit-drinks-tea'
      preLoaderRoute: typeof FruitDrinksTeaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fresh-juice': {
      id: '/fresh-juice'
      path: '/fresh-juice'
      fullPath: '/fresh-juice'
      preLoaderRoute: typeof FreshJuiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/food': {
      id: '/food'
      path: '/food'
      fullPath: '/food'
      preLoaderRoute: typeof FoodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/espresso-hot': {
      id: '/espresso-hot'
      path: '/espresso-hot'
      fullPath: '/espresso-hot'
      preLoaderRoute: typeof EspressoHotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desserts': {
      id: '/desserts'
      path: '/desserts'
      fullPath: '/desserts'
      preLoaderRoute: typeof DessertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coffee': {
      id: '/coffee'
      path: '/coffee'
      fullPath: '/coffee'
      preLoaderRoute: typeof CoffeeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CoffeeRoute: CoffeeRoute,
  ContactRoute: ContactRoute,
  DessertsRoute: DessertsRoute,
  EspressoHotRoute: EspressoHotRoute,
  FoodRoute: FoodRoute,
  FreshJuiceRoute: FreshJuiceRoute,
  FruitDrinksTeaRoute: FruitDrinksTeaRoute,
  IceBlendedRoute: IceBlendedRoute,
  IcedCoffeeRoute: IcedCoffeeRoute,
  MatchaRoute: MatchaRoute,
  MenuRoute: MenuRoute,
  NewDrinkRoute: NewDrinkRoute,
  PennywortRoute: PennywortRoute,
  SmoothiesRoute: SmoothiesRoute,
  SweetDessertsRoute: SweetDessertsRoute,
  VietnameseFoodRoute: VietnameseFoodRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
